version: "3.4"

services:
  app:
    build:
      context: ./
      dockerfile: dockerfile
      target: development
    image: app
    environment:
      PYTHONDONTWRITEBYTECODE: "no-write"
    volumes:
      - .:/usr/src/app
