on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tests
        uses: .github/actions/tests.yml
        id: tests


